/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rental.cosplay;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import rental.cosplay.components.ShadowPanel;

/**
 * Home view panel displaying dashboard statistics.
 * Shows counts of total costumes, rentals, and overdue rentals.
 *
 * @author ASUS
 */
public class HomeView extends javax.swing.JPanel {

    /**
     * Creates new form Home.
     * Initializes components and displays costume statistics.
     */
    public HomeView() {
        initComponents();
        tampilkanJumlahKostum();
        
    }
    
    private void tampilkanJumlahKostum() {
        try {
            DatabaseConnection db = new DatabaseConnection();
            Connection conn = db.getConnection();              
            Statement stmt = conn.createStatement();

            ResultSet rs1 = stmt.executeQuery("SELECT COUNT(*) FROM kostum");
            if (rs1.next()) {
                jJumlahKostum.setText(String.valueOf(rs1.getInt(1))); 
            }

            ResultSet rs2 = stmt.executeQuery("SELECT COUNT(*) FROM rental WHERE status = 'Belum Kembali'; ");
            if (rs2.next()) {
                jJumlahRental.setText(String.valueOf(rs2.getInt(1))); 
            }
            ResultSet rs3 = stmt.executeQuery(
            "SELECT COUNT(*) FROM rental " +
            "WHERE " +
            "(tgl_kembali is not NULL AND tgl_kembali > DATE_ADD(tgl_pinjam, INTERVAL durasi_pinjam DAY)) " +
            "OR (tgl_kembali is NULL AND CURDATE() > DATE_ADD(tgl_pinjam, INTERVAL durasi_pinjam DAY))"
            );
            if (rs3.next()) {
                jTelat.setText(String.valueOf(rs3.getInt(1)));
            }

            

            stmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }    

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelUtama = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTelat = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jJumlahRental = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jJumlahKostum = new javax.swing.JLabel();
        jPanel5 = new ShadowPanel(30,  Color.decode("#F8BBD0"));
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelUtama.setBackground(new java.awt.Color(254, 235, 237));
        PanelUtama.setPreferredSize(new java.awt.Dimension(1050, 720));
        PanelUtama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/cosplay/img/Stiker2.png"))); // NOI18N
        PanelUtama.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/cosplay/img/Stiker1.png"))); // NOI18N
        PanelUtama.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/cosplay/img/Stiker3.png"))); // NOI18N
        PanelUtama.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 190, 190));

        jPanel3.setBackground(new java.awt.Color(255, 248, 248));
        jPanel3.setPreferredSize(new java.awt.Dimension(320, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Kostum Yang Telat Dikembalikan");

        jTelat.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jTelat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTelat.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTelat)
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jTelat)
                .addGap(78, 78, 78)
                .addComponent(jLabel6))
        );

        PanelUtama.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, -1, 211));

        jPanel4.setBackground(new java.awt.Color(255, 248, 248));
        jPanel4.setPreferredSize(new java.awt.Dimension(320, 211));

        jJumlahRental.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jJumlahRental.setText("0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Jumlah Kostum Yang Sedang Dirental");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jJumlahRental))
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jJumlahRental, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jLabel5))
        );

        PanelUtama.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 320, -1));

        jPanel2.setBackground(new java.awt.Color(255, 248, 248));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(320, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jumlah Kostum Yang Tersedia");

        jJumlahKostum.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jJumlahKostum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jJumlahKostum.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jJumlahKostum))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jJumlahKostum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jLabel1))
        );

        PanelUtama.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 211));

        jPanel5.setBackground(new java.awt.Color(255, 248, 248));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("\"Hidup itu panjang kalau kau tahu cara menggunakan nya\"");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("-Seneca-");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        PanelUtama.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1030, 100));

        add(PanelUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JLabel jJumlahKostum;
    private javax.swing.JLabel jJumlahRental;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jTelat;
    // End of variables declaration//GEN-END:variables
}
