/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rental.cosplay;

import formInformasi.FormInformasiView;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;
import rental.cosplay.components.RoundedPanel;
import rental.cosplay.view.kostum.KostumPanel;
import rental.cosplay.view.rental.RentalDataView;

/**
 *
 * @author ASUS
 */
public class MainView extends javax.swing.JFrame {

    NavigationController navigationController;
    AuthController authController;
    UserModel user;
    Color pink = new Color(242, 155, 180);
    Color putih = new Color(254, 239, 244);
    String lokasi = "";

    public MainView() {
        initComponents();

        navigationController = new NavigationController();
        authController = new AuthController();

        navigationController.goTo(this, new HomeView());
        lokasi = "HOME";
        
        HomeButton.setBackground(putih);
        KostumButton.setBackground(pink);
        RentalButton.setBackground(pink);
        RentalData.setBackground(pink);
        LogoutButton.setBackground(pink);

    }

    public JPanel getContentPanel() {
        return ContentPanel;
    }

    private void resetSidebarColor() {
        HomeButton.setBackground(pink);
        KostumButton.setBackground(pink);
        RentalButton.setBackground(pink);
        LogoutButton.setBackground(pink);
        RentalData.setBackground(pink);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SideBarPanel = new RoundedPanel(8, Color.decode("#F7A8C7"));
        jLabel2 = new javax.swing.JLabel();
        HomeButton = new RoundedPanel(30, Color.decode("#F7CAC9"));
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        RentalButton = new RoundedPanel(30, Color.decode("#80AF81"));
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LogoutButton = new RoundedPanel(30, Color.decode("#80AF81"));
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        RentalData = new RoundedPanel(30, Color.decode("#80AF81"));
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        KostumButton = new RoundedPanel(30, Color.decode("#F7CAC9"));
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BodyPanel = new javax.swing.JPanel();
        ContentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setMinimumSize(new java.awt.Dimension(1290, 720));
        MainPanel.setPreferredSize(new java.awt.Dimension(1300, 720));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SideBarPanel.setBackground(new java.awt.Color(248, 187, 208));
        SideBarPanel.setPreferredSize(new java.awt.Dimension(240, 720));
        SideBarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/cosplay/img/LogoKecil.png"))); // NOI18N
        SideBarPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 24, -1, 92));

        HomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeButtonMouseExited(evt);
            }
        });
        HomeButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HomeButtonKeyPressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/cosplay/img/Home.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Home");

        javax.swing.GroupLayout HomeButtonLayout = new javax.swing.GroupLayout(HomeButton);
        HomeButton.setLayout(HomeButtonLayout);
        HomeButtonLayout.setHorizontalGroup(
            HomeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeButtonLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        HomeButtonLayout.setVerticalGroup(
            HomeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SideBarPanel.add(HomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 200, 60));

        RentalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RentalButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RentalButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RentalButtonMouseExited(evt);
            }
        });
        RentalButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RentalButtonKeyPressed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/cosplay/img/Rental.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Rental");

        javax.swing.GroupLayout RentalButtonLayout = new javax.swing.GroupLayout(RentalButton);
        RentalButton.setLayout(RentalButtonLayout);
        RentalButtonLayout.setHorizontalGroup(
            RentalButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RentalButtonLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
        );
        RentalButtonLayout.setVerticalGroup(
            RentalButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RentalButtonLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SideBarPanel.add(RentalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 200, 60));

        LogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseExited(evt);
            }
        });
        LogoutButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LogoutButtonKeyPressed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/cosplay/img/Keluar.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Logout");

        javax.swing.GroupLayout LogoutButtonLayout = new javax.swing.GroupLayout(LogoutButton);
        LogoutButton.setLayout(LogoutButtonLayout);
        LogoutButtonLayout.setHorizontalGroup(
            LogoutButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutButtonLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
        );
        LogoutButtonLayout.setVerticalGroup(
            LogoutButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutButtonLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SideBarPanel.add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 200, 60));

        RentalData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RentalDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RentalDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RentalDataMouseExited(evt);
            }
        });
        RentalData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RentalDataKeyPressed(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/cosplay/img/RentalDataIcon.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Rental Data");

        javax.swing.GroupLayout RentalDataLayout = new javax.swing.GroupLayout(RentalData);
        RentalData.setLayout(RentalDataLayout);
        RentalDataLayout.setHorizontalGroup(
            RentalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RentalDataLayout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
        );
        RentalDataLayout.setVerticalGroup(
            RentalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SideBarPanel.add(RentalData, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 200, 60));

        KostumButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KostumButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KostumButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KostumButtonMouseExited(evt);
            }
        });
        KostumButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KostumButtonKeyPressed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/cosplay/img/Katalog.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Katalog");

        javax.swing.GroupLayout KostumButtonLayout = new javax.swing.GroupLayout(KostumButton);
        KostumButton.setLayout(KostumButtonLayout);
        KostumButtonLayout.setHorizontalGroup(
            KostumButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KostumButtonLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        KostumButtonLayout.setVerticalGroup(
            KostumButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SideBarPanel.add(KostumButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 200, 60));

        MainPanel.add(SideBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, -1));

        BodyPanel.setPreferredSize(new java.awt.Dimension(1050, 720));
        BodyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ContentPanel.setPreferredSize(new java.awt.Dimension(1050, 720));
        ContentPanel.setLayout(new java.awt.BorderLayout());
        BodyPanel.add(ContentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        MainPanel.add(BodyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, 720));

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HomeButtonKeyPressed
        // TODO add your handling code here:\  
    }//GEN-LAST:event_HomeButtonKeyPressed

    private void RentalButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RentalButtonKeyPressed

    }//GEN-LAST:event_RentalButtonKeyPressed

    private void RentalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RentalButtonMouseClicked
        navigationController.goTo(this, new FormInformasiView());
        lokasi = "RENTAL";
        resetSidebarColor();
        RentalButton.setBackground(putih);

    }//GEN-LAST:event_RentalButtonMouseClicked

    private void HomeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButtonMouseClicked
        navigationController.goTo(this, new HomeView());
        resetSidebarColor();
        lokasi = "HOME";
        HomeButton.setBackground(putih);

    }//GEN-LAST:event_HomeButtonMouseClicked

    private void LogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseClicked
        authController.logout(user, this);
    }//GEN-LAST:event_LogoutButtonMouseClicked

    private void LogoutButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LogoutButtonKeyPressed

    }//GEN-LAST:event_LogoutButtonKeyPressed

    private void HomeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButtonMouseEntered
        if (lokasi != "HOME") {
            HomeButton.setBackground(putih);
        }
    }//GEN-LAST:event_HomeButtonMouseEntered

    private void HomeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButtonMouseExited
        if (lokasi != "HOME") {
            HomeButton.setBackground(pink);
        }
    }//GEN-LAST:event_HomeButtonMouseExited

    private void RentalButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RentalButtonMouseEntered
        if (lokasi != "RENTAL") {
            RentalButton.setBackground(putih);
        }
    }//GEN-LAST:event_RentalButtonMouseEntered

    private void RentalButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RentalButtonMouseExited
        if (lokasi != "RENTAL") {
            RentalButton.setBackground(pink);
        }
    }//GEN-LAST:event_RentalButtonMouseExited

    private void LogoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseEntered
        LogoutButton.setBackground(putih);
    }//GEN-LAST:event_LogoutButtonMouseEntered

    private void LogoutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseExited
        LogoutButton.setBackground(pink);
    }//GEN-LAST:event_LogoutButtonMouseExited

    private void RentalDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RentalDataMouseClicked
        // TODO add your handling code here:
        navigationController.goTo(this, new RentalDataView());
        resetSidebarColor();
        lokasi = "RENTALDATA";
        RentalData.setBackground(putih);

                
    }//GEN-LAST:event_RentalDataMouseClicked

    private void RentalDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RentalDataMouseEntered
        // TODO add your handling code here:
        if (lokasi != "RENTALDATA") {
            RentalData.setBackground(putih);
        }
    }//GEN-LAST:event_RentalDataMouseEntered

    private void RentalDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RentalDataMouseExited
        // TODO add your handling code here:
        if (lokasi != "RENTALDATA") {
            RentalData.setBackground(pink);
        }
    }//GEN-LAST:event_RentalDataMouseExited

    private void RentalDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RentalDataKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_RentalDataKeyPressed

    private void KostumButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KostumButtonMouseClicked
        navigationController.goTo(this, new KostumPanel());
        lokasi = "KOSTUM";
        resetSidebarColor();
        KostumButton.setBackground(putih);
    }//GEN-LAST:event_KostumButtonMouseClicked

    private void KostumButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KostumButtonMouseEntered
        // TODO add your handling code here:
        if (lokasi != "KOSTUMBUTTON") {
            KostumButton.setBackground(putih);
        }
    }//GEN-LAST:event_KostumButtonMouseEntered

    private void KostumButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KostumButtonMouseExited
        // TODO add your handling code here:
        if (lokasi != "KOSTUMBUTTON") {
            KostumButton.setBackground(pink);
        }
    }//GEN-LAST:event_KostumButtonMouseExited

    private void KostumButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KostumButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_KostumButtonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* MainPanelCreate and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BodyPanel;
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JPanel HomeButton;
    private javax.swing.JPanel KostumButton;
    private javax.swing.JPanel LogoutButton;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel RentalButton;
    private javax.swing.JPanel RentalData;
    private javax.swing.JPanel SideBarPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
