/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rental.cosplay.view.rental;

//import RentalCosplayModel.RentalModel;
import rental.cosplay.model.RentalModel;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import rental.cosplay.components.ShadowPanel;
import rental.cosplay.controller.RentalController;
import rental.cosplay.controller.FormController;

/**
 * Panel for displaying rental data in a table view.
 * Shows rental records with options to edit and delete.
 *
 * @author Hakim
 */
public class RentalDataView extends javax.swing.JPanel {

    /**
     * Creates new form RentalDataView.
     * Initializes components and loads rental data into the table.
     */
    
    DefaultTableModel tabModel;
    RentalController rentalController;
    List<RentalModel> RentalList;
    
    public RentalDataView() {
        initComponents();
        rentalController = new RentalController();
        
        TableData.setBackground(new Color(255, 240, 245));
        TableData.setSelectionBackground(new Color(255, 240, 245));

        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setBackground(new Color(255, 240, 245));
        TableData.getParent().setBackground(new Color(255, 240, 245));
        TableData.getTableHeader().setBackground(new Color(255, 192, 203)); 
        
        UpdateTable();
    }

    private void UpdateTable(){
        tabModel = (DefaultTableModel) TableData.getModel();
        
        tabModel.setRowCount(0);
        this.RentalList = rentalController.getAllRental();
        
        
        
        if (RentalList != null || !RentalList.isEmpty()) {
            for (RentalModel data : RentalList) {
                String tglKembali = "";
                if (data.getTglKembali() == "null") {
                    tglKembali = "0000-00-00";
                }else{
                    tglKembali = data.getTglKembali();
                }
                tabModel.addRow(new Object[]{
                    data.getIdRental(),
                    data.getNama(),
                    data.getNomorTelp(),
                    data.getAlamat(),
                    data.getTglPinjam(),
                    tglKembali,
                    data.getDurasiPinjam(),
                    data.getStatus(),
                    data.getHarga(),
                    data.getUkuran()
                });
            }
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new ShadowPanel(30,  Color.decode("#F8BBD0"));
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new ShadowPanel(30,  Color.decode("#F8BBD0"));
        jLabel1 = new javax.swing.JLabel();
        jTextFieldInputEdit = new javax.swing.JTextField();
        jLabelDelete = new javax.swing.JLabel();
        jLabelEdit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableData = new javax.swing.JTable();

        jPanel5.setBackground(new java.awt.Color(255, 248, 248));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("\"Hidup itu panjang kalau kau tahu cara menggunakan nya\"");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("-Seneca-");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        setPreferredSize(new java.awt.Dimension(1050, 720));
        setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(254, 235, 237));
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 248, 248));
        jPanel6.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Data Rental Pelanggan");
        jPanel6.add(jLabel1);
        jLabel1.setBounds(40, 20, 242, 29);

        jTextFieldInputEdit.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel6.add(jTextFieldInputEdit);
        jTextFieldInputEdit.setBounds(620, 20, 200, 25);

        jLabelDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/cosplay/img/delete.png"))); // NOI18N
        jLabelDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDeleteMouseClicked(evt);
            }
        });
        jPanel6.add(jLabelDelete);
        jLabelDelete.setBounds(875, 25, 24, 20);

        jLabelEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/cosplay/img/edit.png"))); // NOI18N
        jLabelEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEditMouseClicked(evt);
            }
        });
        jPanel6.add(jLabelEdit);
        jLabelEdit.setBounds(838, 20, 24, 30);

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/cosplay/view/kostum/refresh_icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel6.add(jPanel2);
        jPanel2.setBounds(910, 20, 30, 30);

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 990, 100));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 102));
        jScrollPane1.setForeground(new java.awt.Color(102, 0, 102));

        TableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Rental", "Nama", "No Telp", "Alamat", "Tgl Pinjam", "Tgl Kembali", "Durasi", "Status", "Total Biaya", "Ukuran Kostum"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableData);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 990, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDeleteMouseClicked
//        String nama = jTextFieldInputEdit.getText().trim(); // ngambil nama dari textfield nya
//        
//        if (nama.isEmpty()){
//            JOptionPane.showMessageDialog(this, "Masukan Nama Data yang Akan Dihapus.");
//            return;
//        }
//        
//        FormController controller = new FormController();
//       
//       boolean ada = controller.cekData(nama);
//        if (!ada){
//            JOptionPane.showMessageDialog(this, "Data dengan nama" + nama + "Tidak Ditemukan...");
//            return;
//        }
//        
//        // kalo nama nya ada di db bakalan jalanin ini
//        int konfir = JOptionPane.showConfirmDialog(this, "Anda Yakin Ingin Menghapus Data Nama " + nama + " ? ", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
//        if ( konfir == JOptionPane.YES_OPTION){
//            boolean berhasil = controller.hapusData(nama);
//            
//            if (berhasil){
//                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
//            } else {
//                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus...");
//            }
//        }
//        
        String idRental = jTextFieldInputEdit.getText().trim();
        
        if (idRental.isEmpty()){
            JOptionPane.showMessageDialog(this, "Masukan id Data yang Akan Dihapus.");
            return;
        }
        
        int konfir = JOptionPane.showConfirmDialog(this, "Anda Yakin Ingin Menghapus Data ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        if (konfir == JOptionPane.YES_OPTION){
            FormController controller = new FormController();
            boolean berhasil = controller.hapusData(idRental);
            
            if (berhasil){
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                
            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal Untuk Dihapus...");
            }
        }
    }//GEN-LAST:event_jLabelDeleteMouseClicked

    private void jLabelEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEditMouseClicked
        // TODO add your handling code here:
        String idRental = jTextFieldInputEdit.getText().trim();
        
        if(idRental.isEmpty()){
            JOptionPane.showMessageDialog(this, "Masukan Id yang Ada di Database");
            return;
        }
        
        FormController controller = new FormController();
        RentalModel rental = controller.getDataById(idRental);
        
        
        if (rental == null){
            JOptionPane.showMessageDialog(this, "Data Tidak Ditemukan");
            return;
        }
        
        RentalEditView edit = new RentalEditView(idRental);
        edit.setVisible(true);
        
    }//GEN-LAST:event_jLabelEditMouseClicked

    private void TableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDataMouseClicked
        tabModel = (DefaultTableModel) TableData.getModel();
        int row = TableData.getSelectedRow();
        
        jTextFieldInputEdit.setText(tabModel.getValueAt(row, 0).toString());
    }//GEN-LAST:event_TableDataMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
 
        UpdateTable();
    }//GEN-LAST:event_jPanel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDelete;
    private javax.swing.JLabel jLabelEdit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldInputEdit;
    // End of variables declaration//GEN-END:variables
}
