/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rental.cosplay.view.kostum;

import rental.cosplay.model.KostumModel;

/**
 * Frame for displaying detailed information about a costume.
 * Shows costume name, price, description, and size.
 *
 * @author Hakim
 */
public class DetailKostumFrame extends javax.swing.JFrame {

    /**
     * Creates new form DetailKostumFrame.
     *
     * @param kostum the costume model containing details to display
     */
    public DetailKostumFrame(KostumModel kostum) {
        initComponents();
        
        labelNamaKostum.setText(kostum.getNama());
        labelHargaKostum.setText("Rp. " + String.valueOf(kostum.getHarga()));
        TDeskripsiKostum.setText(kostum.getDeskripsi());
        labelUkuranKostum.setText("Ukuran Kostum : " + kostum.getUkuran());
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelNamaKostum = new javax.swing.JLabel();
        labelHargaKostum = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelUkuranKostum = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TDeskripsiKostum = new javax.swing.JTextArea();
        JBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 187, 208));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(254, 235, 237));
        jPanel2.setPreferredSize(new java.awt.Dimension(580, 100));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Detail Kostum");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 150, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/cosplay/img/LogoKecil.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel3.setBackground(new java.awt.Color(254, 235, 237));
        jPanel3.setPreferredSize(new java.awt.Dimension(580, 470));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNamaKostum.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        labelNamaKostum.setText("Kostum Nobita");
        jPanel3.add(labelNamaKostum, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 410, -1));

        labelHargaKostum.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelHargaKostum.setText("Rp. 350.000");
        jPanel3.add(labelHargaKostum, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Keterangan Ukuran");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        labelUkuranKostum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelUkuranKostum.setText("Ukuran Kostum : Xl, XXL, L");
        jPanel3.add(labelUkuranKostum, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 305, -1, -1));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 96));

        TDeskripsiKostum.setEditable(false);
        TDeskripsiKostum.setColumns(20);
        TDeskripsiKostum.setLineWrap(true);
        TDeskripsiKostum.setRows(5);
        TDeskripsiKostum.setText("Kostum Nobita adalah kostum dari anime doraemon yang memiliki\nbaju warna kuning dan celana berwarna biru, yang dimana kita\nmenyediakan printilan nya yaitu : kacamata, sepatu.");
        jScrollPane1.setViewportView(TDeskripsiKostum);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 110));

        JBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        JBack.setText("Back");
        JBack.setPreferredSize(new java.awt.Dimension(300, 40));
        JBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBackMouseClicked(evt);
            }
        });
        jPanel3.add(JBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBackMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_JBackMouseClicked

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DetailKostumFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DetailKostumFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DetailKostumFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DetailKostumFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DetailKostumFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBack;
    private javax.swing.JTextArea TDeskripsiKostum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelHargaKostum;
    private javax.swing.JLabel labelNamaKostum;
    private javax.swing.JLabel labelUkuranKostum;
    // End of variables declaration//GEN-END:variables

}
