package rental.cosplay.view.kostum;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import rental.cosplay.DatabaseConnection;
import rental.cosplay.controller.KostumController;
import rental.cosplay.model.KostumModel;
import rental.cosplay.components.ComboBox;
import rental.cosplay.components.CustomTextField;
import rental.cosplay.components.RoundedPanel;
import rental.cosplay.components.ShadowPanel;



public class EditKostumView extends javax.swing.JFrame {

    KostumController kostumController;
    DatabaseConnection dbConnection;
    KostumModel kostumModel;
    
    public EditKostumView(KostumModel kostumModel) {
        initComponents();
        
        this.kostumModel = kostumModel;
        
        kostumController = new KostumController();
        dbConnection = new DatabaseConnection();
        
        
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setResizable(false);
        
        loadData(kostumModel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jMainKostum = new javax.swing.JPanel();
        jHeaderKostum = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBodyKostum = new javax.swing.JPanel();
        LabelNamaKostum = new javax.swing.JLabel();
        jNamaKostum = new javax.swing.JTextField();
        LabelHargaKostum = new javax.swing.JLabel();
        jHargaKostum = new javax.swing.JTextField();
        LabelDeskripsiKostum = new javax.swing.JLabel();
        ButtonTambahKostum = new javax.swing.JButton();
        jUkuranKostum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(530, 660));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMainKostum.setBackground(new java.awt.Color(255, 255, 255));

        jHeaderKostum.setBackground(new java.awt.Color(255, 255, 255));
        jHeaderKostum.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Edit Data Kostum");

        javax.swing.GroupLayout jHeaderKostumLayout = new javax.swing.GroupLayout(jHeaderKostum);
        jHeaderKostum.setLayout(jHeaderKostumLayout);
        jHeaderKostumLayout.setHorizontalGroup(
            jHeaderKostumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jHeaderKostumLayout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jHeaderKostumLayout.setVerticalGroup(
            jHeaderKostumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jHeaderKostumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
        );

        jBodyKostum.setBackground(new java.awt.Color(255, 255, 255));
        jBodyKostum.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LabelNamaKostum.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LabelNamaKostum.setText("Nama Kostum");

        jNamaKostum.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jNamaKostum.setToolTipText("");
        jNamaKostum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNamaKostumActionPerformed(evt);
            }
        });

        LabelHargaKostum.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LabelHargaKostum.setText("Harga Kostum");

        jHargaKostum.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jHargaKostum.setToolTipText("");
        jHargaKostum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHargaKostumActionPerformed(evt);
            }
        });

        LabelDeskripsiKostum.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LabelDeskripsiKostum.setText("Ukuran Kostum");

        ButtonTambahKostum.setBackground(new java.awt.Color(204, 255, 204));
        ButtonTambahKostum.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ButtonTambahKostum.setText("EDIT DATA");
        ButtonTambahKostum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonTambahKostumMouseClicked(evt);
            }
        });
        ButtonTambahKostum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahKostumActionPerformed(evt);
            }
        });

        jUkuranKostum.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jUkuranKostum.setToolTipText("");
        jUkuranKostum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUkuranKostumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jBodyKostumLayout = new javax.swing.GroupLayout(jBodyKostum);
        jBodyKostum.setLayout(jBodyKostumLayout);
        jBodyKostumLayout.setHorizontalGroup(
            jBodyKostumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBodyKostumLayout.createSequentialGroup()
                .addGroup(jBodyKostumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBodyKostumLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jBodyKostumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jHargaKostum, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addComponent(LabelHargaKostum, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelNamaKostum, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNamaKostum)
                            .addComponent(LabelDeskripsiKostum, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jUkuranKostum, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)))
                    .addGroup(jBodyKostumLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(ButtonTambahKostum, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jBodyKostumLayout.setVerticalGroup(
            jBodyKostumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBodyKostumLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(LabelNamaKostum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNamaKostum, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelHargaKostum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jHargaKostum, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelDeskripsiKostum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUkuranKostum, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(ButtonTambahKostum, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jMainKostumLayout = new javax.swing.GroupLayout(jMainKostum);
        jMainKostum.setLayout(jMainKostumLayout);
        jMainKostumLayout.setHorizontalGroup(
            jMainKostumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainKostumLayout.createSequentialGroup()
                .addGroup(jMainKostumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jMainKostumLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jHeaderKostum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jMainKostumLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jBodyKostum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jMainKostumLayout.setVerticalGroup(
            jMainKostumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainKostumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jHeaderKostum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jBodyKostum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jMainKostum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jHargaKostumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHargaKostumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHargaKostumActionPerformed

    private void jNamaKostumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNamaKostumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNamaKostumActionPerformed

    private void ButtonTambahKostumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahKostumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonTambahKostumActionPerformed

    private void jUkuranKostumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUkuranKostumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUkuranKostumActionPerformed

    private void ButtonTambahKostumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonTambahKostumMouseClicked
        String id_kostum = kostumController.generateUniqueId(dbConnection.getConnection());
        String nama = jNamaKostum.getText().trim();
        String ukuran = jUkuranKostum.getText().trim();
        String hargaText = jHargaKostum.getText().trim();
        int harga = Integer.parseInt(hargaText);
        
        kostumModel = new KostumModel(kostumModel.getId_kostum(), nama, ukuran, harga);
        boolean isUpdated = kostumController.updateKostum(kostumModel);
        
        if (isUpdated) {
            jOptionPane1.showMessageDialog(this, "Data kostum berhasil diupdate!", "Sukses", jOptionPane1.INFORMATION_MESSAGE);
            this.dispose();
        } else {
            jOptionPane1.showMessageDialog(this, "Gagal mengupdate data kostum!", "Error", jOptionPane1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButtonTambahKostumMouseClicked


    private void loadData(KostumModel kostum) {
        jNamaKostum.setText(kostum.getNama());
        jUkuranKostum.setText(kostum.getUkuran());
        jHargaKostum.setText(String.valueOf(kostum.getHarga()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonTambahKostum;
    private javax.swing.JLabel LabelDeskripsiKostum;
    private javax.swing.JLabel LabelHargaKostum;
    private javax.swing.JLabel LabelNamaKostum;
    private javax.swing.JPanel jBodyKostum;
    private javax.swing.JTextField jHargaKostum;
    private javax.swing.JPanel jHeaderKostum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jMainKostum;
    private javax.swing.JTextField jNamaKostum;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JTextField jUkuranKostum;
    // End of variables declaration//GEN-END:variables
}
