package rental.cosplay.view.kostum;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import rental.cosplay.DatabaseConnection;
import rental.cosplay.controller.KostumController;
import rental.cosplay.model.KostumModel;
import rental.cosplay.components.ComboBox;
import rental.cosplay.components.CustomTextField;
import rental.cosplay.components.RoundedPanel;
import rental.cosplay.components.ShadowPanel;

public class TambahKostumView extends javax.swing.JFrame {

    KostumController kostumController;
    DatabaseConnection dbConnection;
    
    public TambahKostumView() {
        initComponents();
        
        kostumController = new KostumController();
        dbConnection = new DatabaseConnection();

        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setResizable(false);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jMainKostum = new javax.swing.JPanel();
        jHeaderKostum = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBodyKostum = new javax.swing.JPanel();
        LabelNamaKostum = new javax.swing.JLabel();
        jNamaKostum = new javax.swing.JTextField();
        LabelHargaKostum = new javax.swing.JLabel();
        jHargaKostum = new javax.swing.JTextField();
        LabelDeskripsiKostum = new javax.swing.JLabel();
        ButtonTambahKostum = new javax.swing.JButton();
        jUkuranKostum = new javax.swing.JTextField();
        LabelDeskripsi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDeskripsi = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(530, 660));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMainKostum.setBackground(new java.awt.Color(254, 235, 237));

        jHeaderKostum.setBackground(new java.awt.Color(255, 248, 248));
        jHeaderKostum.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jHeaderKostum.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel1.setText("Tambah Data Kostum");
        jHeaderKostum.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 20, 280, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/cosplay/img/LogoKecil.png"))); // NOI18N
        jHeaderKostum.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 15, -1, 92));

        jBodyKostum.setBackground(new java.awt.Color(255, 248, 248));
        jBodyKostum.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LabelNamaKostum.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        LabelNamaKostum.setText("Nama Kostum");

        jNamaKostum.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jNamaKostum.setToolTipText("");
        jNamaKostum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNamaKostumActionPerformed(evt);
            }
        });

        LabelHargaKostum.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        LabelHargaKostum.setText("Harga Kostum");

        jHargaKostum.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jHargaKostum.setToolTipText("");
        jHargaKostum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHargaKostumActionPerformed(evt);
            }
        });

        LabelDeskripsiKostum.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        LabelDeskripsiKostum.setText("Ukuran Kostum");

        ButtonTambahKostum.setBackground(new java.awt.Color(255, 204, 204));
        ButtonTambahKostum.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ButtonTambahKostum.setText("TAMBAH DATA");
        ButtonTambahKostum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonTambahKostumMouseClicked(evt);
            }
        });
        ButtonTambahKostum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahKostumActionPerformed(evt);
            }
        });

        jUkuranKostum.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jUkuranKostum.setToolTipText("");
        jUkuranKostum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUkuranKostumActionPerformed(evt);
            }
        });

        LabelDeskripsi.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        LabelDeskripsi.setText("Deskripsi Kostum");

        jDeskripsi.setColumns(20);
        jDeskripsi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jDeskripsi.setLineWrap(true);
        jDeskripsi.setRows(5);
        jScrollPane1.setViewportView(jDeskripsi);

        javax.swing.GroupLayout jBodyKostumLayout = new javax.swing.GroupLayout(jBodyKostum);
        jBodyKostum.setLayout(jBodyKostumLayout);
        jBodyKostumLayout.setHorizontalGroup(
            jBodyKostumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBodyKostumLayout.createSequentialGroup()
                .addGroup(jBodyKostumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBodyKostumLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(ButtonTambahKostum, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jBodyKostumLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jBodyKostumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelNamaKostum, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNamaKostum)
                            .addGroup(jBodyKostumLayout.createSequentialGroup()
                                .addComponent(LabelHargaKostum, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LabelDeskripsiKostum, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jBodyKostumLayout.createSequentialGroup()
                                .addComponent(jHargaKostum, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jUkuranKostum))
                            .addComponent(LabelDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jBodyKostumLayout.setVerticalGroup(
            jBodyKostumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBodyKostumLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(LabelNamaKostum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNamaKostum, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jBodyKostumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelHargaKostum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDeskripsiKostum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jBodyKostumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jHargaKostum, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jUkuranKostum))
                .addGap(18, 18, 18)
                .addComponent(LabelDeskripsi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(ButtonTambahKostum, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout jMainKostumLayout = new javax.swing.GroupLayout(jMainKostum);
        jMainKostum.setLayout(jMainKostumLayout);
        jMainKostumLayout.setHorizontalGroup(
            jMainKostumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainKostumLayout.createSequentialGroup()
                .addGroup(jMainKostumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jMainKostumLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jBodyKostum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jMainKostumLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jHeaderKostum, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jMainKostumLayout.setVerticalGroup(
            jMainKostumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainKostumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jHeaderKostum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jBodyKostum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jMainKostum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jHargaKostumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHargaKostumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHargaKostumActionPerformed

    private void jNamaKostumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNamaKostumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNamaKostumActionPerformed

    private void ButtonTambahKostumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahKostumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonTambahKostumActionPerformed

    private void jUkuranKostumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUkuranKostumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUkuranKostumActionPerformed

    private void ButtonTambahKostumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonTambahKostumMouseClicked
        String id_kostum = kostumController.generateUniqueId(dbConnection.getConnection());
        String nama = jNamaKostum.getText().trim();
        String ukuran = jUkuranKostum.getText().trim();
        String hargaText = jHargaKostum.getText().trim();
        int harga = Integer.parseInt(hargaText);
        String deskripsi = jDeskripsi.getText().trim();

        // Validasi data
        /*if (namaObat.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama obat tidak boleh kosong", "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (kategoriObj == null || kategoriObj.toString().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kategori harus dipilih", "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (exp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tanggal kadaluarsa tidak boleh kosong", "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (hargaText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harga tidak boleh kosong", "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (stokText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Stok tidak boleh kosong", "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int harga;
        int stok;
        try {
            harga = Integer.parseInt(hargaText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga harus berupa angka", "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            stok = Integer.parseInt(stokText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Stok harus berupa angka", "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String kategori = kategoriObj.toString().trim();
*/
        // Buat model kostum
        KostumModel kostumModel = new KostumModel(id_kostum, nama, ukuran, harga, deskripsi);

        // Tambah kostum ke database
        if (kostumController.tambahKostum(kostumModel)) {
            jOptionPane1.showMessageDialog(this, "Data Kostum berhasil disimpan dengan ID: " + id_kostum);
            clearInput();
        } else {
            jOptionPane1.showMessageDialog(this, "Gagal menyimpan data Kostum", "Kesalahan", jOptionPane1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButtonTambahKostumMouseClicked

    
    private void clearInput() {
        jNamaKostum.setText("");
        jHargaKostum.setText("");
        jUkuranKostum.setText("");
        jDeskripsi.setText("");
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahKostumView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahKostumView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahKostumView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahKostumView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahKostumView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonTambahKostum;
    private javax.swing.JLabel LabelDeskripsi;
    private javax.swing.JLabel LabelDeskripsiKostum;
    private javax.swing.JLabel LabelHargaKostum;
    private javax.swing.JLabel LabelNamaKostum;
    private javax.swing.JPanel jBodyKostum;
    private javax.swing.JTextArea jDeskripsi;
    private javax.swing.JTextField jHargaKostum;
    private javax.swing.JPanel jHeaderKostum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jMainKostum;
    private javax.swing.JTextField jNamaKostum;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jUkuranKostum;
    // End of variables declaration//GEN-END:variables
}
